name = "residential-ip-finder"
compatibility_date = "2024-01-01"

[env.production]
route = "residential-ip-finder.pages.dev"

[build]
command = ""
cwd = ""
watch_dir = ""

[[pages_build_output_dir]]
value = "."